document.write('have a good day')
console.log('have a happy day')


// var 
// decaration 
var a

// initilization
var a = 45

// re-initilization
a = 800

// re-decaration 
var a=896

console.log(a)

// let
// decaration 
let a1

// initilization
a1 = 45;

// re-initilization
a1 = 800


// re-decaration 
//! let a1=896

console.log(a1)

// const
// decaration 
// const a

// initilization
const c = 45

// re-initilization
// c = 741

console.log(c)

// re-decaration 
// const c = 896